// automatically generated by the FlatBuffers compiler, do not modify

/**
 * @const
 * @namespace
 */
var Flatbuf = Flatbuf || {};

/**
 * @constructor
 */
Flatbuf.Person = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {Flatbuf.Person}
 */
Flatbuf.Person.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {Flatbuf.Person=} obj
 * @returns {Flatbuf.Person}
 */
Flatbuf.Person.getRootAsPerson = function(bb, obj) {
  return (obj || new Flatbuf.Person).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {Flatbuf.Person=} obj
 * @returns {Flatbuf.Person}
 */
Flatbuf.Person.getSizePrefixedRootAsPerson = function(bb, obj) {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Flatbuf.Person).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {number}
 */
Flatbuf.Person.prototype.homeIndex = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
Flatbuf.Person.prototype.officeIndex = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
Flatbuf.Person.prototype.supermarketIndex = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
Flatbuf.Person.prototype.hospitalIndex = function() {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? this.bb.readInt16(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
Flatbuf.Person.prototype.countyIndex = function() {
  var offset = this.bb.__offset(this.bb_pos, 12);
  return offset ? this.bb.readInt16(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
Flatbuf.Person.prototype.name = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 14);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns {number}
 */
Flatbuf.Person.prototype.age = function() {
  var offset = this.bb.__offset(this.bb_pos, 16);
  return offset ? this.bb.readUint8(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
Flatbuf.Person.prototype.maleFemale = function() {
  var offset = this.bb.__offset(this.bb_pos, 18);
  return offset ? this.bb.readUint8(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
Flatbuf.Person.prototype.race = function() {
  var offset = this.bb.__offset(this.bb_pos, 20);
  return offset ? this.bb.readUint8(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
Flatbuf.Person.startPerson = function(builder) {
  builder.startObject(9);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} homeIndex
 */
Flatbuf.Person.addHomeIndex = function(builder, homeIndex) {
  builder.addFieldInt32(0, homeIndex, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} officeIndex
 */
Flatbuf.Person.addOfficeIndex = function(builder, officeIndex) {
  builder.addFieldInt32(1, officeIndex, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} supermarketIndex
 */
Flatbuf.Person.addSupermarketIndex = function(builder, supermarketIndex) {
  builder.addFieldInt32(2, supermarketIndex, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} hospitalIndex
 */
Flatbuf.Person.addHospitalIndex = function(builder, hospitalIndex) {
  builder.addFieldInt16(3, hospitalIndex, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} countyIndex
 */
Flatbuf.Person.addCountyIndex = function(builder, countyIndex) {
  builder.addFieldInt16(4, countyIndex, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} nameOffset
 */
Flatbuf.Person.addName = function(builder, nameOffset) {
  builder.addFieldOffset(5, nameOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} age
 */
Flatbuf.Person.addAge = function(builder, age) {
  builder.addFieldInt8(6, age, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} maleFemale
 */
Flatbuf.Person.addMaleFemale = function(builder, maleFemale) {
  builder.addFieldInt8(7, maleFemale, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} race
 */
Flatbuf.Person.addRace = function(builder, race) {
  builder.addFieldInt8(8, race, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
Flatbuf.Person.endPerson = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} homeIndex
 * @param {number} officeIndex
 * @param {number} supermarketIndex
 * @param {number} hospitalIndex
 * @param {number} countyIndex
 * @param {flatbuffers.Offset} nameOffset
 * @param {number} age
 * @param {number} maleFemale
 * @param {number} race
 * @returns {flatbuffers.Offset}
 */
Flatbuf.Person.createPerson = function(builder, homeIndex, officeIndex, supermarketIndex, hospitalIndex, countyIndex, nameOffset, age, maleFemale, race) {
  Flatbuf.Person.startPerson(builder);
  Flatbuf.Person.addHomeIndex(builder, homeIndex);
  Flatbuf.Person.addOfficeIndex(builder, officeIndex);
  Flatbuf.Person.addSupermarketIndex(builder, supermarketIndex);
  Flatbuf.Person.addHospitalIndex(builder, hospitalIndex);
  Flatbuf.Person.addCountyIndex(builder, countyIndex);
  Flatbuf.Person.addName(builder, nameOffset);
  Flatbuf.Person.addAge(builder, age);
  Flatbuf.Person.addMaleFemale(builder, maleFemale);
  Flatbuf.Person.addRace(builder, race);
  return Flatbuf.Person.endPerson(builder);
}

/**
 * @constructor
 */
Flatbuf.PersonArray = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {Flatbuf.PersonArray}
 */
Flatbuf.PersonArray.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {Flatbuf.PersonArray=} obj
 * @returns {Flatbuf.PersonArray}
 */
Flatbuf.PersonArray.getRootAsPersonArray = function(bb, obj) {
  return (obj || new Flatbuf.PersonArray).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {Flatbuf.PersonArray=} obj
 * @returns {Flatbuf.PersonArray}
 */
Flatbuf.PersonArray.getSizePrefixedRootAsPersonArray = function(bb, obj) {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Flatbuf.PersonArray).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {number} index
 * @param {Flatbuf.Person=} obj
 * @returns {Flatbuf.Person}
 */
Flatbuf.PersonArray.prototype.people = function(index, obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new Flatbuf.Person).__init(this.bb.__indirect(this.bb.__vector(this.bb_pos + offset) + index * 4), this.bb) : null;
};

/**
 * @returns {number}
 */
Flatbuf.PersonArray.prototype.peopleLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
Flatbuf.PersonArray.prototype.junk = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
Flatbuf.PersonArray.startPersonArray = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} peopleOffset
 */
Flatbuf.PersonArray.addPeople = function(builder, peopleOffset) {
  builder.addFieldOffset(0, peopleOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Offset>} data
 * @returns {flatbuffers.Offset}
 */
Flatbuf.PersonArray.createPeopleVector = function(builder, data) {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
Flatbuf.PersonArray.startPeopleVector = function(builder, numElems) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} junk
 */
Flatbuf.PersonArray.addJunk = function(builder, junk) {
  builder.addFieldInt32(1, junk, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
Flatbuf.PersonArray.endPersonArray = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} offset
 */
Flatbuf.PersonArray.finishPersonArrayBuffer = function(builder, offset) {
  builder.finish(offset);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} offset
 */
Flatbuf.PersonArray.finishSizePrefixedPersonArrayBuffer = function(builder, offset) {
  builder.finish(offset, undefined, true);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} peopleOffset
 * @param {number} junk
 * @returns {flatbuffers.Offset}
 */
Flatbuf.PersonArray.createPersonArray = function(builder, peopleOffset, junk) {
  Flatbuf.PersonArray.startPersonArray(builder);
  Flatbuf.PersonArray.addPeople(builder, peopleOffset);
  Flatbuf.PersonArray.addJunk(builder, junk);
  return Flatbuf.PersonArray.endPersonArray(builder);
}

// Exports for Node.js and RequireJS
this.Flatbuf = Flatbuf;
